### ISSUE TITLE
Need assistance with module version-control

### ISSUE THREAD

**Issue by mboedker** [dxc-technology/online-devops-dojo#58]
How do I open data.sql ?

I tried to write open data.sql but nothing happens.

**Comment by pberthonneau** [comment]
I guess you are in step 3 of 8 of Continuous integration module.
> Head over to your copy of the Pet Clinic application on GitHub, and navigate to the file in the **src/main/resources/db/hsqldb** folder named data.sql

If you click on `src/main/resources/db/hsqldb` link you'll see on the right the GitHub links page with the link to your own `data.sql` highlighted. Click on it, scroll up to see the pencil and follow the instructions to make the change.

Let me know if you have a concern or close this issue.
Thanks for attending the Online DevOps Dojo!

**Comment by mboedker** [comment]
Hi

I have now added line 24 to data.sql:

[cid:image001.png@01D642EC.19CF4F20]

And saved the changes, but when I follow the steps in DevOps Dojo VersionControl, it says that there are nothing to commit and everything is up to date:

[cid:image002.png@01D642EC.19CF4F20]

So if I press “Continue”, I don’t have a “Pull request” in GitHub for “Horse”.

What am I doing wrong ?

Med venlig hilsen

Michael Bødker
Senior Developer
DXC Eclipse, Northern Europe

M: +45 2060 9727
mboedker@dxc.com<mailto:mboedker@dxc.com>

**Comment by pberthonneau** [comment]
You have no difference between your working branch and master branch, this is why you cannot create a new PR.

Actually your [master branch](https://github.com/mboedker/pet-clinic/commits/master) has already the change line #24, which means that you committed your change directly in master, which is not a good practice when you want a peer review (which is the case here). Then I guess you went off rails from step 3 instructions.

I advise you to revert the change on your master:
- git checkout master
- git revert 6a2bbf8 (which is the commit hash [here](https://github.com/mboedker/pet-clinic/commits/master)
- git push origin master

then close and forget your branches https://github.com/mboedker/pet-clinic/branches, except master.
Then restart from the beginning of step 3.

If you don't succeed you can also delete the pet-clinic repository (from tab setting) and replay the Welcome.

**Comment by pberthonneau** [comment]
In lack of answer, I'm closing this. Re-open if needed.
