### ISSUE TITLE
Enhance clarity on Verison Control module being required before Continuous Integration

### ISSUE THREAD

**Issue by adamdmharvey** [dxc-technology/online-devops-dojo#76]
The Version Control module must be completed before the Continuous Integration module, because it includes defining "horse" as a type in the Pet clinic, before then referencing that type in the Continuous Integration module.  If students skip straight to CI, the database tests will always fail.

While it's roughly referred to, we should enhance the clarity that in fact you _must_ complete Version Control module as a requirement before attempting the Continuous Integration module; they're not entirely independent.

_Originally posted by @rosnermd in https://github.com/dxc-technology/online-devops-dojo/issues/75#issuecomment-726931700_

**Comment by tom-halpin** [comment]
Thank you @adamdmharvey, @rosnermd for suggesting this improvement and to @pberthonneau for resolving
