### ISSUE TITLE
Octocats as images for the dojo?

### ISSUE THREAD

**Issue by cpswan** [dxc-technology/online-devops-dojo#83]
**Is your feature request related to a problem? Please describe.**
Not problem related

**Describe the solution you'd like**
DXC Dojo team figure out if we'd like to use Octocat icons for the characters instead of (or in addition to?) their existing cartoon images.

**Describe alternatives you've considered**
We could replace the cartoons, or we could also maybe create Octocats to be what the characters would choose.

**Additional context**
From GitHub Universe 2020 Enterprise Track discussion [#625](https://github.com/githubevents/universe2020/discussions/625) suggested by @iceicys

**Comment by tom-halpin** [comment]
@cpswan https://github.com/dxc-technology/online-devops-dojo/pull/85 submitted in response, idea being to use Dojo Octocat to introduce Dojo in Welcome module.

**Comment by tom-halpin** [comment]
Dojo Octcat lives

![image](https://user-images.githubusercontent.com/20931122/102216928-c7709d80-3ed3-11eb-8b3c-31674f86c54b.png)

We may have to introduce him to the dojo mascot in time.

Closing, other folks are free to use as they see fit in other modules if they desire

PS the OctoCat development tool is cool
