### ISSUE TITLE
Need assistance with module continuous-integration

### ISSUE THREAD

**Issue by Reddidgy** [dxc-technology/online-devops-dojo#92]
**Describe the issue**
Hi. I'm stupid man :( Tried to use ngrok inside the provided linux machine in tutor for understanding what that machine can do. Looks like my public IP was banned
62.4.55.86. Could you please return me? **I promiss not to do that again and I will just learning DevOps path!**
Thank you in advance

**To Reproduce**
1. Go to any page with KVM on right hand side and tutor on the left
2. See white screen

**Expected behavior**
Working interface of both big tutor elements

**Additional context**
Sorry again :(

**Comment by ojacques** [comment]
@Reddidgy - trying is learning, and that's the purpose of the online DevOps Dojo!
However, I'm afraid there is nothing we can do. This is a normal protection mechanism from Katacoda. You may try to contact them - https://katacoda.com/ and see if they can lift the ban.
