### ISSUE TITLE
Need assistance with module version-control

### ISSUE THREAD

**Issue by ponkey1** [dxc-technology/online-devops-dojo#94]
.prepare.sh/ command not working

**Comment by tom-halpin** [comment]
@ponkey1 sorry to hear you are having an issue.

To enable us help you can you forward a screen shot and / or the text of the error message you are getting

**Comment by ponkey1** [comment]
Thanks for attending.

I am in the "Step 2" of module "Version Control" of "DevOps Dojo" program. When I execute the command:
./prepare.sh

I get below message:
-bash: ./prepare.sh: No such file or directory

I have also:
1. Regenerated the token once and execute the command.
2. Restarted the exercise before it again including regenerating code 

Still no change and get the same message:
-bash: ./prepare.sh: No such file or directory

I am not able to move further in program, pls look into it.
![Err msg](https://user-images.githubusercontent.com/89219791/130202370-fee43b75-efc9-47da-8451-2d5bc3ba93eb.PNG)

**Comment by tom-halpin** [comment]
@ponkey1 Thank you, I have reproduced the issue and will prepare a fix.

**Comment by ponkey1** [comment]
Thanks @tom-halpin , I have did R&D and found that I was required to change the directory to pet-clinic, before executing the command as shell script prepare.sh was in the directory pet-clinic. I did the same and it worked.

Thanks a lot.

**Comment by tom-halpin** [comment]
@ponkey1 thank you, I was about to suggest that to you, I will add a note to the content so that future students are informed of th need to do that.

**Comment by ponkey1** [comment]
Hi @tom-halpin ,
I would suggest two pies:
1. Either by default, we are taken to the pet-clinic folder, or
2. a command should be added in the course content on this slide to change the directory.
I think second option is better.

**Comment by tom-halpin** [comment]
Closing the issue, as your immediate issue is resolved and an update will be issued for the dojo.

Hope you enjoy the rest of the dojo @ponkey1
