### ISSUE TITLE
How to get the Dojo Belts (White, Green and Yellow) and regarding flow of the course.

### ISSUE THREAD

**Issue by ponkey1** [dxc-technology/online-devops-dojo#96]
I am going through DevOps Dojo sessions. I have followed the sequence and have completed below in the order:
1. Welcome and Setup
2. Leading Change
3. Version Control
4. Continuous Integration
5. Shift Security Left
6. Value Stream Mapping

But, after "Value Stream Mapping" instead of going to "Post Incident Practices", I was taken to "DevOps Kaizen", 

I would like to know is it by design or is it a bug in the flow.

I have completed DevOps Kaizen also, but after the same instead of "Value Stream Mapping", I am taken to O'Reilly's KataCode page showing that I do not have access. Attached is its image. Pls let know is it ok or it is an error.

I will complete the "Post Incident Practices" session now directly.  Would like to know, now how can I get White, Green and Yellow belts as I have gone through complete session. Pls guide.

Seek a quick response as I wish to complete it today.

Rgds,
Pawan
![Err msg 1](https://user-images.githubusercontent.com/89219791/130252293-0a5edaf6-8ede-46ab-ac7f-571094bcfac2.PNG)

**Comment by tom-halpin** [comment]
@ponkey1 thank you for reporting the issue, once you have completed the modules listed at https://dxc-technology.github.io/about-devops-dojo/modules/ you have completed the DevOps dojos

The white, yellow and black are internal / customer facing dojos, in fact these are the source of most of the open sourced dojos.

If you are interested in exploring the Pet-Clinic multi-verse there is also the online product engineering dojo  https://dxc-technology.github.io/about-pe-dojo/

**Comment by ponkey1** [comment]
@tom-halpin , I watched the video on site before starting the sessions. As per the same, these dojos can be used on Linkedin as Badges. My question is how can I get these Badges. 

Will it be mailed to me  or shared on my Workday / DXC University ? 

Pls guide.

**Comment by tom-halpin** [comment]
Badges are issued for the internal dojo's taken via DXC University, there are no badges for the open sourced dojo which is available to all.

**Comment by ponkey1** [comment]
So, none of these Dojos will be available for use. But, this is contradictory to what was told in the video by the creators.....
![DevOps Dojos](https://user-images.githubusercontent.com/89219791/130264163-374a045d-76ae-48e4-a14c-e29bbf3e8c1a.PNG)

**Comment by tom-halpin** [comment]
Those are the internal dojos, I was referring to, which video are you referring to?

**Comment by ponkey1** [comment]
I am referring to the video under DevOps@DXC and one of the video links in under About. 

https://dxc-technology.github.io/about-devops-dojo/devopsatdxc/

In that it specified, that DXC created Dojo to promote adoption of the DevOps and the same can be used by the people who complete it,

Pls check and let know.

**Comment by tom-halpin** [comment]
That covers DevOps at DXC, where we have the internal dojos, following their success we open sourced some of the content, in this the online DevOps dojo

**Comment by ponkey1** [comment]
@tom-halpin may we have a chat on Teams to close this subject. My email is pawan.sharma4@dxc.com

**Comment by ponkey1** [comment]
Thanks @tom-halpin  for all the support during this course. It is a lovely course. I practically have this life in varied roles of Coder, Project Manager, Architects.....Great work by you and whole of the team.

**Comment by tom-halpin** [comment]
Thanks @ponkey1 always nice to get feedback, even nicer to get positive feedback
